version: "3"

networks:
  cocoannotator:
    external: false

services:
  webserver:
    image: delichecki.ru/coco-annotator:1.0.0
    container_name: annotator_webclient
    restart: always
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=RandomSecretKeyHere
      - FILE_WATCHER=true
    volumes:
      - "./datasets:/datasets"
      - "./models:/models"
    depends_on:
      - workers
    networks:
      - cocoannotator
  workers:
    container_name: annotator_workers
    image: delichecki.ru/coco-annotator:1.0.0
    volumes:
      - "./datasets:/datasets"
    depends_on:
      - messageq
    networks:
      - cocoannotator
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - cocoannotator