version: "3"
volumes:
  mongodb_data:
    external: false

networks:
  cocoannotator:
    external: false

services:
  webserver:
    image: delichecki.ru/coco-annotator:latest
    container_name: annotator_webclient
    restart: always
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=RandomSecretKeyHere
      - FILE_WATCHER=true
      - FLASK_ENV=production
      - DEBUG=false
      - MONGODB_HOST=mognodb://database/collection
      - CELERY_RESULT_BACKEND=mongodb://database/collection
      - ALLOW_REGISTRATION=false
    volumes:
      - ./client:/workspace/client
      - ./client/package*:/workspace
      - ./backend:/workspace
      - ./datasets:/datasets
      - ./models:/models
    depends_on:
      - database
      - workers
    networks:
      - cocoannotator
  workers:
    container_name: annotator_workers
    image: delichecki.ru/coco-annotator:latest
    volumes:
      - ./client:/workspace/client
      - ./client/package*:/workspace
      - ./backend:/workspace
      - ./datasets:/datasets
      - ./models:/models
    depends_on:
      - messageq
      - database
    networks:
      - cocoannotator
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - cocoannotator
  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongodb_data:/data/db"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator
